name: AvAAntiCheat
version: 1.21 
main: com.nolan.ava.AvAAntiCheat
api-version: 1.21
authors: [Nolan]
description: An anti-cheat system detecting flight, spam, and PvP logging.
commands:
  ac:
    description: AvA Anti-Cheat administration commands.
    # 2. USAGE CHANGE: Reflects all new subcommands in the Java code
    usage: /ac <status|start <1-4>|stop|kick <player>|checkop <player>|reload>
    permission: ava.admin
    permission-message: You don't have permission to use the AvA Anti-Cheat commands.
  secretdisable:
    description: Secretly disables the anti-cheat for testing (requires OP or specific user).
    usage: /<command>
permissions:
  ava.admin:
    description: Allows access to all AvA Anti-Cheat administration commands.
    default: op